sudo: false
language: node_js
node_js:
- "6"
git:
  depth: 10
before_script:
  - npm prune
script: npm run $COMMAND
after_success:
  - npm run semantic-release
env:
  matrix:
  - COMMAND=test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
